apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: "amd64"
      containers:
      - name: {{ .Chart.Name }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.targetPort }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
        {{- if .Values.enableResourceConstraints }}
{{ toYaml .Values.resources | indent 10 }}
        {{- else }}
          {}
        {{- end }}
        securityContext:
          privileged: false
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 30
      dnsPolicy: "ClusterFirst"
